<?php
/**
 * Created by PhpStorm.
 * User: yangchunrun
 * Date: 17/7/24
 * Time: 上午11:47
 */

namespace app\ajax\controllers;


use yii\filters\Cors;
use yii\helpers\ArrayHelper;
use yii\web\Controller;

class BaseController extends Controller
{

    public $enableCsrfValidation =false;



    public function beforeAction($action)
    {
        header("Access-Control-Allow-Origin: *");
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {

        if (\Yii::$app->request->isAjax && is_array($result)) {
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        }

        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

    public function response($data, $code = 1000, $message = '')
    {
        echo json_encode(['message' => $message, 'code' => $code, 'result' => $data]);
        exit;
    }
}